version: 2.1

commands:
  install_deps:
    steps:
      - run:
          name: Install Deps
          command: |
            mkdir -p ./src/node_modules
            npm install --prefix ./src

jobs:
  ci-build:
    docker:
      - image: circleci/node:lts
    environment:
      JEST_JUNIT_OUTPUT_DIR: test-output
    steps:
      - checkout
      - install_deps
      - run: linting
        command: |
          npm run test-lint --prefix ./src
      - run:
          name: run tests
          command: |
            npm run test-unit --prefix ./src
            mkdir -p test-output

  

      

workflows:
  build-and-packge:
    jobs:
      - ci-build
      
