version: 2.1

commands:
  install_deps:
    steps:
      - run:
          name: Install Deps
          command: |
            mkdir -p ./src/node_modules
            npm install --prefix ./src

jobs:
  ci-build:
    docker:
      - image: circleci/node:lts
    environment:
      JEST_JUNIT_OUTPUT_DIR: /home/circleci/project/test-output
    steps:
      - checkout
      - install_deps
      - run: 
          name: run linting tests
          command: |
            npm run test-lint --prefix ./src
      - run:
          name: run unit tests
          command: |
            npm run test-unit --prefix ./src
            mkdir -p test-output
      - store_test_results:
          path: /home/circleci/project/test-output/
          
  sast:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: 
          name: Install NodeJsScan
          command: |
            sudo apt update
            sudo apt install python3-pip
            pip3 install nodejsscan
      - run:
          name: run NodeJsScan
          command: |
            nodejsscan -d ./ -o sast-output.json
      - store_artifacts:
          path: sast-output.json
      - run:
          name: Parse sast output
          command: |
            # exit with non-zero if there is any security issues
            exit $(cat sast-output.json | jq .total_count.sec)
  
  integration-tests:
    docker:
      - image: circleci/node:lts
      - image: mongo:4.0
    environment:
      APP_PORT: 5000
      JEST_JUNIT_OUTPUT_DIR: /home/circleci/project/integration-test-output
    steps:
      - checkout
      - install_deps
      - run:
          name: run integration tests
          command: |
            npm run test-integration --prefix src/
            mkdir -p integration-test-output
      - store_test_results:
          path:  /home/circleci/project/integration-test-output
  
  end-to-end-tests:
    docker:
      - image: circleci/node:lts
      - image: mongo:4.0
    environment:
      APP_PORT: 5000
      JEST_JUNIT_OUTPUT_DIR: /home/circleci/project/e2e-tests-output
    steps:
      - checkout
      - intsall_deps
      - run:
          name: run e2e tests
          commands: |
            npm run test-e2e --prefix ./src
            chmod +x scripts/e2e-ci.sh
            ./scripts/e2e-ci.sh
            mkdir -p e2e-tests-output
      - store_test_results:
          path: /home/circleci/project/e2e-tests-output

  pack:
    docker:
      - image: circleci/node:lts
    environment:
      NODE_ENV: production
    steps:
      - checkout
      - install_deps
      - store_artifacts:
          path: ./

      

workflows:
  build-and-packge:
    jobs:
      - ci-build
      - sast:
          requires:
            - ci-build
      - integration-tests:
          requires:
            - ci-build
            - sast
      - end-to-end-tests:
          requires:
            - ci-build
            - sast
            - integration-tests
      - pack: 
          requires:
            - ci-build
            - sast
          filters:
            branches:
              only:
                - master
